### ISSUE TITLE
Trying to work the demo - get an error

### ISSUE THREAD

**Issue by jensamunch** [datocms/nextjs-demo#10]
Hi all,

I follow the instructions in the README and use the following url:

This is my .env file

```
NEXT_EXAMPLE_CMS_DATOCMS_API_TOKEN=xxxx
NEXT_EXAMPLE_CMS_DATOCMS_PREVIEW_SECRET=supersecret
``` 

When I use the following URL:
http://localhost:3000/api/preview?secret=supersecret

I get the following error

```
Error: Error serializing `.subscription.environment` returned from `getStaticProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

![image](https://user-images.githubusercontent.com/1650140/108738004-0aca3680-752b-11eb-8489-7d77b113df98.png)

**Comment by jensamunch** [comment]
I also try this url but same error:
http://localhost:3000/api/preview?secret=supersecret&slug=mistakes-tourists-make-on-their-first-trip-abroad

**Comment by jensamunch** [comment]
also it would be nice to have in the README what the recommendation is for how to decide when to show the top alert.js banner. you wouldn't want that showing by default for all visitors to the site...

**Comment by stefanoverna** [comment]
Hey @jensamunch, I think this is the issue, can you confirm? https://github.com/datocms/nextjs-demo/commit/4f31a8d050e823f33a521d43ec9fe6d7c477b1fd

Regarding the alert... on a production website it would make much sense to just show it when preview mode is active!

**Comment by matjack1** [comment]
I cannot reproduce anymore. I think it has been fixed meanwhile. But if you can reproduce feel free to reopen.
