### ISSUE TITLE
Rendering blocks with multiple fields in StructuredText component errors with `Element type is invalid`?

### ISSUE THREAD

**Issue by callumflack** [datocms/nextjs-demo#11]
I'm probably not doing this right. I tried adding multiple fields to a block inside a Structured Text block from Dato.

My Next.js app says `Element type is invalid` when I pipe it into the [`post-body` component](https://github.com/datocms/nextjs-demo/blob/master/components/post-body.js) from your demo.

Here's what my query looks like, might be the best thing to assert first:

![image](https://user-images.githubusercontent.com/749885/109294157-8d7b2a80-7878-11eb-8563-393aa12cd1d4.png)

**Comment by stefanoverna** [comment]
Hey @callumflack! The error doesn't ring a bell..could you give me more info? If you could share the repo itself that would be great, or otherwise the exact use you make of the `<StructuredText />` component (and the `package-lock.json`). Thanks!

**Comment by callumflack** [comment]
Thanks @stefanoverna, here's the [slug file's line](https://github.com/callumflack/lep/blob/bc153868e4c0ba0d8f7ccb5192c5df349fd19761/pages/reports/%5Bslug%5D.js#L98) where I attempted to import a component using `<StructuredText />`.

(It's a real rough early set-up on this project…)

**Comment by stefanoverna** [comment]
@callumflack you just need to upgrade react-datocms 😉 

```
-    "react-datocms": "1.2.6",
+    "react-datocms": "1.5.5",
```

https://github.com/stefanoverna/lep/commit/aa1ee727be3f93b71195f7c28d1e6c16b6889d46

**Comment by callumflack** [comment]
D'oh, thanks @stefanoverna
