### ISSUE TITLE
Console logs 'Can't resolve 'fsevents' repeatedly under Windows 10

### ISSUE THREAD

**Issue by Ross-Angus** [datocms/nextjs-demo#12]
**Issue:**
When installing the blog demo under Windows 10, the Node package `fsevents` (which only works under MacOS) seems to be installed as a dependency. This does not seem to cause any functional issues, but clutters the console with unnecessary warnings, which repeat with every page refresh.

**Hardware used**

- Windows 10  (version 20H2)
- Firefox V. 89.0
- Node 14.17.0

**Comment by matjack1** [comment]
unfortunately it's a dependency of one of our dependencies, we cannot do much here :(
