### ISSUE TITLE
CORS error with  tiny-json-http

### ISSUE THREAD

**Issue by blueglobalnl** [datocms/nextjs-demo#26]
Hello, 

Somehow when I update tiny-json-http or use Axios instead I get the following CORS error in preview mode: 

Access to fetch at 'https://graphql-listen.datocms.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field x-include-drafts is not allowed by Access-Control-Allow-Headers in preflight response.

I assume the error originates from the useQuerySubscription, hook.

**Comment by blueglobalnl** [comment]
After further inspection the issue seems to be related to node_modules/datocms-listen

**Comment by stefanoverna** [comment]
Should be solved now, the issue was server side.. can you check?
