### ISSUE TITLE
Unable to create the NextJS / DatoCms demo project

### ISSUE THREAD

**Issue by fatwreck** [datocms/nextjs-demo#35]
When I click "Start Free Project" (Found here: https://www.datocms.com/marketplace/starters/nextjs-template-blog) I run into a message on the DatoCMS site saying, "We're sorry, but some features of DatoCMS that this template requires, are not available on your plan."

I'm trying to debug why my dynamic pages aren't returning any data in this function:

```
export default async function Page({ params }) {
  const { isEnabled } = draftMode();

  const pageRequest = getPageRequest(params.slug);
  console.log('data pageRequest ->', pageRequest);  ---> Returns object with PAGE_CONTENT_QUERY [my long query object], includeDrafts: false, variables: { slug: 'openbook' }
  const data = await performRequest(pageRequest);
  console.log('data WORK PAGE ->', data); ---> undefined
```

Two different problems. I want to fix the data request, but thought I'd point out the hurdle with the demo project as well. (cloned the starter project and used the env key:value from an old existing datocms project btw. Everything is good and done except for these dynamic pages)

**Comment by marcelofinamorvieira** [comment]
Hello @fatwreck you probably have a legacy free plan on your account thats causing this issue, can you try to create a new free account with a different email on Dato and try to initiate the starter there?

**Comment by fatwreck** [comment]
That was it, thanks @marcelofinamorvieira
