### ISSUE TITLE
Question or potential bug in api/getAllPostsWithSlug

### ISSUE THREAD

**Issue by dmeijboom** [datocms/nextjs-demo#4]
Hi there!

I'm new to NextJS but upon developing my blog using this demo template I noticed a missing `await` for the `getAllPostsWithSlug` function. Is this simply an error or is there some Javascript magic I don't know about?

https://github.com/datocms/nextjs-demo/blob/807d7136f6076089d5722d9dc0d85a018b6c8cbf/lib/api.js#L63

Thanks :)

**Comment by souljuse** [comment]
The logic has completely changed. Closing this issue!
