### ISSUE TITLE
Demo build failing on Vercel

### ISSUE THREAD

**Issue by Rohitkrops** [datocms/nextjs-demo#8]
Hi,

I tried to launch the Nextjs Blog Demo, but the build is failing on Vercel. I followed the following steps:
1. Choose the Nextjs Blog Demo from marketplace and hit "Start free project" 
2. Things went well and a dialogue box came up 
<img width="928" alt="Screenshot 2021-01-04 at 6 01 46 PM" src="https://user-images.githubusercontent.com/20735862/103535759-4f383f00-4eb7-11eb-9ffd-f551705ec982.png">
3. When I tried to access the site, it was down.
4. The build failed with this error.
<img width="1099" alt="Screenshot 2021-01-04 at 6 00 41 PM" src="https://user-images.githubusercontent.com/20735862/103535826-71ca5800-4eb7-11eb-92ce-034b0cf0ed5b.png">

Waiting for your reply 😀

**Comment by Rohitkrops** [comment]
Hi, can someone please check this, I am stuck.

**Comment by stefanoverna** [comment]
Hi @Rohitkrops, sorry for the delay. We're working with Vercel to solve this, will update you as soon as we have news!

**Comment by samuelgoddard** [comment]
Changing my Vercel environment to use Next.js defualts as it's build settings fixed this for me, I dunno if that's any help?
<img width="708" alt="Screenshot 2021-01-07 at 20 38 17" src="https://user-images.githubusercontent.com/8715435/103942459-51ed9b00-5128-11eb-9a06-8c55e3360894.png">

**Comment by stefanoverna** [comment]
Yes, Vercel API atm is unable to detect frameworks, we're working with them for a solution, thanks!

**Comment by Rohitkrops** [comment]
@samuelgoddard I changed build settings as you shared above. When redeploying, I am presented with this new error. 
<img width="1038" alt="Screenshot 2021-01-09 at 8 10 56 AM" src="https://user-images.githubusercontent.com/20735862/104081136-af7e0680-5252-11eb-8c73-919c5342c7a7.png">

**Comment by Rohitkrops** [comment]
I think it would be better if I build it myself from scratch. 
Anyway, thanks for your help
